version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    user: root
    restart: unless-stopped
    volumes:
      - $HOME/.grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - metrics

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    user: root
    restart: unless-stopped
    volumes:
      - $HOME/.prometheus/config:/etc/prometheus
      - $HOME/.prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - metrics

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    hostname: loki
    volumes:
      - $HOME/.loki/config:/etc/loki
    command:
      - '--config.file=/etc/loki/local-config.yaml'
    ports:
      - 3100:3100
    networks:
      - metrics

  spring-boot:
    build: .
    container_name: demo
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - metrics

networks:
  metrics:
    driver: bridge