---
kind: Namespace
apiVersion: v1
metadata:
  name: "{{.Chart.Name}}-{{.Values.env}}"
  labels:
    app: {{.Chart.Name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  revisionHistoryLimit: {{.Values.deployment.revisionHistoryLimit}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          ports:
            - containerPort: {{.Values.container.port}}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: demo.db.credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo.db.credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo.db.credentials
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.env}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
